apiVersion: v1
kind: Service
metadata:
  name: scouter-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scouter-agent
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: sct6180
      protocol: TCP
      port: 6180
      targetPort: 6180
    - name: sct6188
      protocol: TCP
      port: 6188
      targetPort: 6188
    - name: scttcp
      protocol: TCP
      port: 6100
      targetPort: 6100
    - name: sctudp
      protocol: UDP
      port: 6100
      targetPort: 6100
